const menuData = {
    "Antipasti": [
      { name: "Antipasto Campagnola", description: "bruschetta con rucola, pomodori secchi, melanzane grigliate", price: 8 },
      { name: "Crudo a fette e mozzarella di Bufala", price: 10 },
      { name: "Carpaccio di Bresaola", description: "bresaola, rucola, scaglie di grana, sale, olio", price: 10 },
      { name: "Antipasto all’italiana", price: 9 },
      { name: "Crudo S. Daniele alla carrettiera", price: 10 },
      { name: "Cacio al forno", price: 7 },
      { name: "Cacio pizza", description: "pomodoro, mozzarella, salsiccia piccante o salsiccia fresca", price: 9 },
      { name: "Bruschetta alla foggiana con rucola", price: 1 },
      { name: "Tagliere di affettati e formaggi misti piccolo", price: 14 },
      { name: "Tagliere di affettati e formaggi misti grande", price: 20 },
      { name: "Antipasti della casa", price: 12 },
      { name: "Tris di bruschette", description: "Mortadella, stracciatella, granella di pistacchi, Capocollo, pomodori semi dry, glassa balsamica", price: 6 },
      { name: "Ortaggi Caserecci", description: "melanzane, zucchine, peperoni grigliati, fagiolini bolliti", price: 7 },
    ],
    "Fritture": [
      { name: "Sfiziosità miste", price: 4 },
      { name: "Patatine fritte", price: 3.5 },
      { name: "Pirofila piccola di patatine fritte", price: 5.5 },
      { name: "Pirofila grande di patatine fritte", price: 8 },
      { name: "Bastoncini di pollo (5 pezzi)", price: 4 },
      { name: "Crocchette di patate (5 pezzi)", price: 3.5 },
      { name: "Mozzarelline impanate (6 pezzi)", price: 3.5 },
      { name: "Olive all’ascolana (6 pezzi)", price: 3.5 },
      { name: "Chele di granchio (4 pezzi)", price: 3.5 },
    ],
    "Insalate": [
      { name: "Insalata Casereccia", description: "lattuga, pomodori, cetrioli, mais, rucola, cipolla, sale, olio", price: 4 },
      { name: "Leone", description: "insalata mista, olive, Philadelphia, pomodori secchi", price: 7 },
      { name: "Scorpione", description: "lattuga, radicchio, rucola, mais, tonno", price: 6.5 },
      { name: "Acquario", description: "lattuga, gamberetti, cozze, grana", price: 7 },
    ],
    "Carni alla Brace": [
      { name: "Grigliata mista", description: "2 salsiccia, 1 agnello, 2 paccanelli, 2 arrosticini, 1 collo di maiale", price: 15 },
      { name: "Salsiccia (4 capi)", price: 8 },
      { name: "Fettina di vitello", price: 7 },
      { name: "Agnello (4 pezzi)", price: 8 },
      { name: "Torcinelli cad.", price: 1.2 },
      { name: "Paccanelli cad.", price: 1.2 },
      { name: "Costatina di maiale", price: 1.5 },
      { name: "Arrosticini (10 pezzi)", price: 8 },
      { name: "Cotoletta di pollo + patatine fritte", price: 8 },
      { name: "Misto paccanelli e torcinelli (8 pezzi)", price: 8 },
    ],
    "Pizze Rosse": [
      { name: "Margherita", description: "pomodoro, fior di latte, basilico, olio evo", price: 6 },
      { name: "Pizza Regina", description: "pomodoro, bufala campana, basilico, olio evo", price: 7 },
      { name: "Marinara", description: "pomodoro, origano, olio evo", price: 4 },
      { name: "Diavola", description: "pomodoro, fior di latte, salsiccia piccante, olive", price: 7 },
      { name: "Capricciosa", description: "pomodoro, fior di latte, carciofi, funghi champignon, prosciutto cotto", price: 8 },
      { name: "Wurstel", description: "pomodoro, fior di latte, wurstel", price: 6 },
      { name: "Salumi vari", description: "pomodoro, fior di latte, cotto, wurstel, ventricina, salsiccia fresca, crudo e fette", price: 8 },
      { name: "Speciale", description: "pomodoro, fior di latte, funghi champignon, salsiccia piccante, cacio, olive", price: 7.5 },
      { name: "Bresaola", description: "pomodoro, fior di latte, bresaola, rucola, scaglie di grana", price: 8 },
      { name: "Al Tonno", description: "pomodoro, fior di latte, tonno, capperi", price: 6 },
      { name: "Parma", description: "pomodoro, fior di latte, crudo a fette, scaglie di grana, bocconcini, rucola", price: 8 },
      { name: "Napoletana", description: "pomodoro, fior di latte, acciughe, capperi", price: 6.5 },
      { name: "Calabrese", description: "pomodoro, fior di latte, ventricina, prosciutto cotto", price: 7 },
      { name: "Affumicata", description: "pomodoro, fior di latte affumicato, funghi champignon, speck", price: 8 },
      { name: "Boscaiola", description: "pomodoro, fior di latte, funghi porcini, salsiccia fresca, scaglie di grana", price: 9 },
    ],
    "Pizze Bianche": [
      { name: "Piada", description: "olio evo, sale, origano", price: 3 },
      { name: "Quattro Formaggi", description: "fior di latte, gorgonzola, emmenthal, galbanino", price: 7 },
      { name: "Patanara", description: "fior di latte, patate al forno, prosciutto cotto, scaglie di grana", price: 7 },
      { name: "Pupa", description: "fior di latte, gorgonzola, melanzane grigliate, speck, scaglie di grana, rosmarino", price: 7.5 },
      { name: "Vegetariana", description: "fior di latte, zucchine, melanzane, peperoni grigliati, asparagi, spinaci", price: 7.5 },
      { name: "Pizza Bartolo", description: "fior di latte affumicato, pomodorini freschi, rucola", price: 7 },
      { name: "Pizza Matteo", description: "fior di latte, pesto alla genovese, mortadella, stracciatella, granella di pistacchi", price: 8 },
      { name: "Biancaneve", description: "fior di latte, prosciutto cotto, funghi champignon, bocconcini alla panna", price: 7 },
      { name: "Crudaiola", description: "fior di latte, rucola, scaglie di grana, crudo a fette, bocconcini alla panna", price: 8 },
      { name: "Montanara", description: "fior di latte, crema di rape, salsiccia piccante, scaglie di grana", price: 8 },
      { name: "Pizza Arianna", description: "fior di latte, gorgonzola, scaglie di grana, noci", price: 8 },
    ],
   "Calzoni": [
      { name: "Calzone Farcito", description: "fior di latte, crema di ricotta, pepe, salame napoli", price: 8 },
      { name: "Calzone Bijou", description: "fior di latte, funghi, prosciutto cotto, bocconcini, crudo a fette", price: 9 },
      { name: "Calzone alla Parmigiana", description: "pomodoro, fior di latte, melanzane a funghetto, scaglie di grana, basilico, olio evo", price: 8 },
    ],
    "Pizze Speciali": [
      { name: "Al Campanile", description: "bordo ripieno di ricotta, pomodoro, fior di latte, pomodorini, rucola, crudo a fette", price: 8 },
      { name: "La Rustica", description: "vellutata di datterino giallo, fior di latte, pomodoro semi dry, capocollo, burrata", price: 9 },
      { name: "L’Imperatrice", description: "fior di latte, cime di rapa, fior di latte, salsiccia fresca, pomodorini semi dry, stracciatella, mollica fritta", price: 10 },
      { name: "A Mia Moglie", description: "crema di zucca, fior di latte, melanzane a funghetto, guanciale croccante, chips di parmigiano", price: 11 },
      { name: "La Fata Bianca", description: "crema di zucchine, fior di latte, speck croccante, burrata", price: 10 },
      { name: "Fumé", description: "fior di latte affumicato, funghi porcini, porchetta", price: 9 },
      { name: "4 Stagioni a Modo Mio (4 gusti)", description: "fior di latte, cime di rapa, guanciale croccante, pomodoro, fior di latte, basilico, fior di latte, patate al forno, porchetta, scaglie di grana, fior di latte, pomodorini, rucola, scaglie di grana, perle di glassa balsamica", price: 10 },
    ],
    "Birre": [
      { name: "Beck’s 0,33 l", price: 3.5 },
      { name: "Ceres 0,33 l", price: 4 },
      { name: "Heineken 0,33 l", price: 3 },
      { name: "Nastro Azzurro 0,33 l", price: 3 },
      { name: "Corona 0,33 l", price: 4.5 },
      { name: "Tuborg 0,66 l", price: 4 },
      { name: "Heineken 0,66 l", price: 4 },
      { name: "Nastro Azzurro 0,66 l", price: 4 },
      { name: "Peroni alla spina 0,20 l", price: 4.5 },
      { name: "Peroni alla spina 0,40 l", price: 6 },
    ],
    "Bevande": [
      { name: "Coca cola / Coca cola Zero 0,33 l", price: 2.5 },
      { name: "Fanta / Chino / Sprite 0,33 l", price: 2.5 },
      { name: "Estathé Limone / Pesca 0,33 l", price: 2.5 },
      { name: "Coca Cola / Fanta litro", price: 4 },
      { name: "Acqua Minerale litro", price: 2 },
    ],
    "Vini": [
      { name: "Bianco / Rosso / Rosato 0,75 l", price: 2.5 },
      { name: "Vini Imbottigliati", price: 10 },
      { name: "Prosecco", price: 10 },
      { name: "Spumante Dolce", price: 9.5 },
    ],
    "Liquori": [
      { name: "Amari", price: 3 },
      { name: "Limoncello", price: 3 },
      { name: "Grappa Bianca", price: 4 },
      { name: "Grappa Barricata", price: 4 },
    ],
    "Dolci": [
      { name: "Dolci della casa", price: 3.5 },
      { name: "Cassatine di Tommasino", price: 5 },
      { name: "Dessert Carte d’Or", price: 5 },
      { name: "Dessert Carte d’Or cocco", price: 5 },
      { name: "Sorbetto al limone", price: 5 },
    ],
    "Extra": [
      { name: "Coperto", price: 1 },
      { name: "Aggiunta / Variazioni", price: 1 },
      { name: "Aggiunta di bufala", price: 2 },
    ],
  }

  export default menuData